server:
  port: 5001
  accesstoken: eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3MjAzNzUxOTksImlkIjoiMzIwMmQwYjUtNTRmZi00ZWYzLWI1YmQtNGQ5OTg3Y2Y4N2FjIn0.SY69ZGjKvd8O6UPjFqAgAYHR_yVpBjcMUUbjjn_p8PrUhmmQcMHeYZLeWI7FHXNSxn_BlvkDnkqpVjq2Gqz7Ag
